/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i firewalld1_interface.h -p :firewalld1_interface.cpp dbus_interfaces/org.fedoraproject.FirewallD1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "firewalld1_interface.h"
/*
 * Implementation of interface class OrgFedoraprojectFirewallD1Interface
 */

OrgFedoraprojectFirewallD1Interface::OrgFedoraprojectFirewallD1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1Interface::~OrgFedoraprojectFirewallD1Interface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1DirectInterface
 */

OrgFedoraprojectFirewallD1DirectInterface::OrgFedoraprojectFirewallD1DirectInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1DirectInterface::~OrgFedoraprojectFirewallD1DirectInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1PoliciesInterface
 */

OrgFedoraprojectFirewallD1PoliciesInterface::OrgFedoraprojectFirewallD1PoliciesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1PoliciesInterface::~OrgFedoraprojectFirewallD1PoliciesInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1ZoneInterface
 */

OrgFedoraprojectFirewallD1ZoneInterface::OrgFedoraprojectFirewallD1ZoneInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1ZoneInterface::~OrgFedoraprojectFirewallD1ZoneInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusIntrospectableInterface
 */

OrgFreedesktopDBusIntrospectableInterface::OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusIntrospectableInterface::~OrgFreedesktopDBusIntrospectableInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusPropertiesInterface
 */

OrgFreedesktopDBusPropertiesInterface::OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPropertiesInterface::~OrgFreedesktopDBusPropertiesInterface()
{
}

